### ISSUE TITLE
How well does AudioBook listening work?

### ISSUE THREAD

**Issue by Inrego** [macr0dev/Audiobooks.bundle#10]
It's not really an issue, and I haven't even tried this plugin.

But I'm interested in knowing how well the AudioBook listening experience is with Plex..
Can someone show off a little how it works?

**Comment by matthew-hodgins** [comment]
So far it's not the greatest. Plex has a feature to remember your position for a library but I've found that it doesn't work most of the time. I was hoping to swap from phone to web to Roku with the same book, but no luck.

**Comment by Inrego** [comment]
Damn. I guess I'll stick to trying to get Emby to work. Support should be better there, but I cannot get it to work. But if all else fails, I can make a plugin and custom AudioBook app for Emby.
