### ISSUE TITLE
Biography = ? tag

### ISSUE THREAD

**Issue by petrmenzel** [macr0dev/Audiobooks.bundle#14]
With field from tags is represented by **Biography**?

<img width="543" alt="001" src="https://user-images.githubusercontent.com/12900736/28504127-c9df6734-7011-11e7-84e4-23a099015f51.PNG">
<img width="410" alt="002" src="https://user-images.githubusercontent.com/12900736/28504128-c9f6d8ce-7011-11e7-9346-b32178b8d8d4.PNG">

**Comment by macr0dev** [comment]
None of your tags provide any of that information other than providing the Author's name for lookups.  
  
there are some built-in functions in Plex that are pulling "artist info" from last.fm.  You can go look the guy up there and see everything from his bio.  I plan on writing something to do that in the future.  I just haven't found a great source of info that's also easy to search and scrape.  audible itself is useless on that front.

**Comment by Swipular** [comment]
Not sure about easy to scrape but I think goodreads.com is probably the best source available.

**Comment by macr0dev** [comment]
the problem with goodreads is that there is no way to just search for an author.  you can search for a book, then go to the author page from that book.  But I haven't found any advanced search functions that can give me direct access to author pages.

**Comment by jmeosbn** [comment]
Does that matter though? Presumably you got the author name from a book’s info anyway?

**Comment by macr0dev** [comment]
Having the author's name and using that information to connect directly to an author's page are not the same thing.  Realistically, you need to be able to search for that author.  Take George R R Martin for example.  Do you built the URL for the page with or without the periods?  Or Davin L Golemon.  Is his page David L Golemon, or David Lynn Golemon.  It's not just "knowing" the authors name, you have to also "know" where the page is on the site that you'r looking for.  And how that author's name is spelled or entered can vary from one book listing to another, and from one site to another.
