### ISSUE TITLE
Multiple authors handled as one

### ISSUE THREAD

**Issue by pax0707** [macr0dev/Audiobooks.bundle#15]
I've noticed this issue with The Science of Discworld series - http://www.audible.co.uk/series?asin=B019PJR7FM

Authors are separated by ";" and show as single entry.

![plex_2017-09-04_16-59-25](https://user-images.githubusercontent.com/3536230/30032070-29adcf5e-9194-11e7-81d5-b3426b9e3d48.png)

**Comment by pax0707** [comment]
Also: https://www.audible.com/pd/Sci-Fi-Fantasy/The-Folklore-of-Discworld-Audiobook/B008FR70AI/

https://imgur.com/a/ewjC2

**Comment by macr0dev** [comment]
Yeah, so here's the problem.  This came up recently in a discussion regarding short story collections.  And what it comes down to is the difference between how we view Plex, and how Plex ACTUALLY treats media.

Out of instinct, we view Plex as an index or a database.  We want to see our media listed and identified multiple ways.  Unfortunately, Plex is REALLY more like a shelf in your house.  If I go to my old CD collection, I pretty much only have one copy of each item there.  Which means that while I can sort this collection any way I like (by length, by artist, by title, by genre, etc) any one CD can only appear one time in the collection on the shelf.

Plex is no different hear.  We can tag media for sorting, filtering etc.  But each item (in this case an audiobook) can only appear once.  So what do we do?  I considered parsing the authors as individual names, but to what end?  I can still only assign one author as the artist of the album.  I considered parsing them to be used as genre tags.  But then we enter the arena of having so many tags they become useless.  If every genre, author, narrator, etc is a separate tag there becomes to many to wade through.  
  
I'm open to suggestions if you have any ideas on what to do with multiple authors.  Our biggest problem is going to be the limitations that exist within Plex's audio libraries.

**Comment by pax0707** [comment]
I was not aware of that Plex limitation...

**Comment by macr0dev** [comment]
no worries.  I wish we didn't have it.  But, then again even if I could make an album appear by  several different authors/artists I'd bitch and complain that when I view my albums by title it shows up like 5 times in a row.  lol.  
  
Oh well.
