### ISSUE TITLE
Issue with search strings that include special characters like Single Quotation mark. '

### ISSUE THREAD

**Issue by dethrophes** [macr0dev/Audiobooks.bundle#16]
I stumbled across what looks like a bug in the audible site, if you use the http: version it seems to mangle escaped characters when redirecting to the https, site after playing with it for a bit I figured out that just directly using hte https url avoids the issue.

https://github.com/dethrophes/Audiobooks.bundle/commit/575d55cdd2c0f858c9479d8810114d36e56bf197

**Comment by macr0dev** [comment]
Interesting.  I haven't run into that one yet.  Any problems using ssl with any of the international sites?

**Comment by dethrophes** [comment]
Not that I'm aware of.

If you want an example to try out.
https://www.audible.com/search?searchTitle=L%27il+du+Temps&x=41&ipRedirectOverride=true
Search Results for Title: 
L'il du Temps
vs
http://www.audible.com/search?searchTitle=L%27il+du+Temps&x=41&ipRedirectOverride=true
Search Results for Title: 
L&apos;il du Temps

**Comment by macr0dev** [comment]
That's really interesting.  They probably wouldn't have ever noticed it since everything on their site redirects to https anyway.  I'll add that in to me code.  Thanks for the heads up.

**Comment by dethrophes** [comment]
Yhea I know, it really had be scratching my head, ... as I thougt it was a problem with the agent, however after playing around with it for a bit I figured out it had to be a problem with the site... 

lol, just wondering if I should try to report it .... somehow..

**Comment by macr0dev** [comment]
Eh, I'm sure it's not something that would ever come up for someone just using the website.  Just people like us doing stuff they may frown on anyway.  HA!
