### ISSUE TITLE
MAybe cleanup the tags and add the narrators as the producers?

### ISSUE THREAD

**Issue by dethrophes** [macr0dev/Audiobooks.bundle#18]
I noticed that sometimes the genres etc... can be a bit unclean, it helps to strip, them.
It is also a pretty standard convention to set the producer to the narrator, from what I can see so that probably doesn't hurt either. 
e.g.`
        metadata.genres.add(series.strip())
        for c in narrator.split(','):
            metadata.genres.add(c.strip())
        metadata.genres.add(genre1.strip())
        metadata.genres.add(genre2.strip())

        metadata.producers.clear()
        for c in narrator.split(','):
            metadata.producers.add(c.strip())
        
        # other metadata

`

**Comment by macr0dev** [comment]
I've been thinking about this one, and while I don't completely disagree with the logic of your placement it just doesn't work for one of my goals.  One of the things I wanted to be able to do was 'filter' by the narrator.  Since you can't filter by Producer, I can't see moving the information to that field.

**Comment by dethrophes** [comment]
I don't see why not, The way I have done it the Narrator is also still a
tag. As such there is no downside.

**Comment by macr0dev** [comment]
ooooh.  I thought you were talking about moving it.  You'd mentioned the genres being 'unclean' and in my mind I interpreted that as 'cluttered'.

I get what you're saying now.  Yeah.  I'll get that thrown in there in a couple of days.

**Comment by macr0dev** [comment]
heads up.... Audible did a major re-write of their page and broke everything.  I've got a new issue started on it already.  gonna try to work on it tomorrow and this weekend.  Gonna keep notes on it over in that issue.

**Comment by macr0dev** [comment]
I was looking at this one the other day, and I couldn't actually find where you were talking about putting them.  I don't see a 'producer' entry on the album properties inside plex.  Is there some hidden metadata I'm not aware of?

**Comment by dethrophes** [comment]
Here
https://github.com/dethrophes/Audiobooks.bundle/blob/master/Contents/Code/__init__.py#L534

**Comment by macr0dev** [comment]
OK, but where does it show up in Plex?  Between Plex and PlexPy I can't see where that data is displayed anywhere.  Is it just being stored in the database somewhere and isn't accessible?

**Comment by macr0dev** [comment]
Cleaning up and closing old issues.  Closing./
