### ISSUE TITLE
Updating or changing Artist and Album titles after initial creation

### ISSUE THREAD

**Issue by jmeosbn** [macr0dev/Audiobooks.bundle#29]
Hey there, does anybody know of a way (within the plex framework) to change the artist or album title after it's search result has been chosen?
  
i.e. I have an `[unknown artist]` but a good match on the title - which of course, also gives me the author - however the only place I can seem to affect the artist name is when providing an initial hit in the artist search function (at which point I haven't got the album info!). And after that it's too late.

Similarly, I want to use basic book titles (without `: some subtitle`, `, Book 1 of the blah blah` or whatever) so can trim those off - but again, have to do so in the search function. It would be helpful to show those full titles for hints in the search results and then strip only them in the update function*.

* related: I'd actually like to store the entire title in the `title_sort` field - which I can do fine. However, I'd still like it to serve it's purpose and be free of the "determiner" prefixes ('A|An|The') etc.

  Any ideas how to do this without a hardcoded list per language? I thought of reading the existing tag and adding to that, but like most apps, that is `None` unless explicitly defined (while still showing a sort value in the UI).

Cheers!

**Comment by macr0dev** [comment]
The agent pretty much has to work off of how Audible.com lists the book on their site.  And in my own library I've even noticed changes in title of books in series where it previously include "Title of Series, Book 2: A Story" one day and then just "A Story" the next.

There's no way to predict how they're going to do it, and no way for the scraper to "decide" which part of the title is the series name vs just the title name.  

As for wanting to change the display name, You can edit the Album Name after it's matched and then lock the field in the Plex Web Interface.  If you're wanting them to display or sort a certain way, that's kind of your only option.  Just like with Movies.

Sorry.
