### ISSUE TITLE
Anyway to have alexa resume position when playing via my dot?  Anyway to skip ahead/back via voice interface?

### ISSUE THREAD

**Issue by arooni** [macr0dev/Audiobooks.bundle#30]
Hey!

Thanks so much for what you've created... it does work great on my android devices... but now, I'd like to get Alexa Dot integration working. I can say

"Alexa, ask Plex to play the album "Norse Mythology"" and she'll do it... trouble is, Plex doesn't seem to remember where it was last playing, and I don't often have time to listen to the book all at once. I've also tried "Alexa, ask plex to resume the album Norse Mythology" with no dice Ideas?

2) is there any way to skip ahead 5 minutes, 10 minutes go back 5 minutes etc via your dot skill?

Thanks again!!

**Comment by macr0dev** [comment]
Playing catch-up on on issues after being busy for quite a while.

This isn't a feature that can be controlled by the metadata agent. All this agent can do is provide data to store/display as part of the library.  What you're referencing is a function of interaction between Plex and Alexa.  Sorry.
