### ISSUE TITLE
Add alternate data source: OpenLibrary

### ISSUE THREAD

**Issue by d2dyno** [macr0dev/Audiobooks.bundle#33]
I am trying to settle on a solid source for audiobook metadata (even for manual scraping), and have yet to find a great source. One I did find that seems to encourage an open-database type metadata, is OpenLibrary. They also seem to have an API, so could that be used? https://openlibrary.org/developers

**Comment by macr0dev** [comment]
The only problem with a site like this is that there are infinitely more books than something like TV Shows or Movies.  Which means that crowdsourcing that kind of data is going to be a LOT of work and is likely to fall on the people who want to use the plugin in the first place.  So, while I'm not against a site like this - I can already tell that even for my own uses I'd be adding QUITE a few books to make it work.

Also, the covers aren't in the right format - nor does there appear to be a place to enter audiobook specific types of data.

**Comment by macr0dev** [comment]
Cleaning up old issues.  Closing.
