### ISSUE TITLE
[German] author's latest book is found in automatic/manual search instead of correct title

### ISSUE THREAD

**Issue by rix1337** [macr0dev/Audiobooks.bundle#35]
Thanks for this great project.

I am trying to add "Der nasse Fisch" from the german Audible site, but it is neither automatically nor manually matchable.

Edit: my initial assumption was probably wrong.

**Comment by macr0dev** [comment]
can you drop me a link directly to the book on the audible.de site?  I want to make sure I'm looking at the right one for you.

**Comment by rix1337** [comment]
Sure thing: 
https://www.audible.de/pd/Der-nasse-Fisch-Hoerbuch/B075R8N7GB

Another example being the king series "the dark tower".
All titles are matched as https://www.audible.de/pd/Der-Outsider-Hoerbuch/383714285X 

Instead of this one, for example: https://www.audible.de/pd/Wind-Hoerbuch/B0095T9T40

Seems to apply to various other titles as well. Automatic and manual matching fails, while the auther is correctly matched.

For example all Dan Brown books are matched as the latest one "Origin".

**Comment by macr0dev** [comment]
So, as a test I took a single MP3 and set it up with the album name Der nass Fisch and the album artist as Volker Kutscher and it automatically matched.  I dropped the Gereon Rath 1.  At one time, Audible likely had them listed on the same line as the title.  But in recent months they've gotten better about splitting the specific book titles out from the series name.

I can dig into another of the examples you provided if you want to include a screen shot of the MP3 tags for one of the tracks and a quick dump of the logs where it tries to match it.

But I honestly think doing the simpler book title without including the series name in it will solve a big chunk of your problems.

Thanks!

**Comment by rix1337** [comment]
Thanks for the quick replies.

I'll try that.

Any idea why manually searching might not work in these cases? Is this agent always relying on the tags?

**Comment by macr0dev** [comment]
You bet!  So, the tricky thing about manual searching is that it still needs to have that author tag to narrow things down.  Plex also (for some unknown reason) tries to use the title of the first track to match against the moment you click 'fix match'.  But then when you type in manually and hit search it will use what you typed in - along with the author/album artist.

Hope all of that helps.

**Comment by nevrion** [comment]
I have exactly the same problem. No matter which Steven King audiobook I add, it's always tagged as the most recently added book on Audible.de. 2 weeks ago it was "Der Outsider" now all as "Erhebung" which was published on Audible on 09.11.2018.

Furthermore, all Harry Potter audiobooks are recognized as Harry Potter und der Stein der Weisen - Gesprochen von Rufus Beck.

**Comment by macr0dev** [comment]
Can you give me some more detail about your books?  What would be useful is a direct link to the book you WANT it to match to as well as the 'Album' and 'Album Artist' tag in your files.

**Comment by nevrion** [comment]
Of course, I have tried it with several authors and several books, I always have the same result, the book is scrawled as the last published book or the one currently the most successful of the author. (In the example Harry Potter)

Example 1 :

Stephen King - Es

Filename : Es

Tags: 
	Artist: Stephen King
	Album : Es
	Album-Artist: Stephen King
	Genre: David Nathan / Fantasy / Horror
	Date: 2011


Audible Link : https://www.audible.de/pd/Es-Hoerbuch/B004WNC388?qid=1543256703&sr=sr_1_1&ref=a_search_c3_lProduct_1_1&pf_rd_p=34e3b439-2a21-4dff-af95-98a7a74a1f67&pf_rd_r=P90DQ1RMMT185AY4R323&

Plex always does it and all the other Stephen King books to :

Erhebung 

https://www.audible.de/pd/Erhebung-Hoerbuch/3837144623?qid=1543256824&sr=sr_1_1&ref=a_search_c3_lProduct_1_1&pf_rd_p=34e3b439-2a21-4dff-af95-98a7a74a1f67&pf_rd_r=BD5X5BD473AR70SW4HC2&




Harry Potter (there are 2 versions in Germany) are always scanned as Harry Potter und der Stein der Weisen gesprochen von Rufus Beck, regardless of which book I scan

https://www.audible.de/pd/Harry-Potter-und-der-Stein-der-Weisen-Gesprochen-von-Rufus-Beck-Hoerbuch/B01M02FJ7A?qid=1543256877&sr=sr_1_2&ref=a_search_c3_lProduct_1_2&pf_rd_p=34e3b439-2a21-4dff-af95-98a7a74a1f67&pf_rd_r=2FPQJH3AXQD2VW7GSPP0&

as well ... as :

Filename: Harry Potter und der Feuerkelch (Harry Potter 4)

Tags:

	Artist: J.K. Rowling
	Album: Harry Potter und der Feuerkelch (Harry Potter 4)
	Album-Artist: J.K. Rowling
	Genre: Harry Potter / Felix von Manteuffel / Fantasy /
	Date: 2015


Audible Link : https://www.audible.de/pd/Harry-Potter-und-der-Feuerkelch-Harry-Potter-4-Hoerbuch/B017XW6YJS?ref=a_series_c4_lProduct_1_4&pf_rd_p=ce651f84-6682-4e9e-a31c-75adf221c2f2&pf_rd_r=ZBXSXN33DR6JPRRJC02F&


Thank you for your help

**Comment by macr0dev** [comment]
thanks for so much detail.  I'll do some tests and see what's going on.  Can you confirm for me how you have your agent configured?  Are you manually selecting audible.de or letting it auto-select based on a German language library?  (It shouldn't matter I just want to mimic your setup)

**Comment by nevrion** [comment]
Plex is in german and the agent is on audible.de

**Comment by macr0dev** [comment]
OK.  It looks like audible made a url tweak on their .de site to bring it more in line with their .com site.  I'll check the other foreign language sites also before updating the repo but for now, you can test this change:

Line 36, change `u'searchTitle='` to `u'title='`

**Comment by nevrion** [comment]
Thanks, that works fine :) My wife will love you :D

**Comment by rix1337** [comment]
I like that too. :+1:

**Comment by rix1337** [comment]
Can confirm this to be working.

**Comment by macr0dev** [comment]
Looks like I just never went back and closed this one.  Closing.
