### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by robwent** [macr0dev/Audiobooks.bundle#39]
I've unzipped the contents into the plugins folder but nothing is showing up in the admin area.

I tried to install the unofficial apps store to install that way and from that repo I saw that plex is discontinuing the use of plugins.

Sooo, does this still work and I just haven't installed properly?

**Comment by robwent** [comment]
I uploaded as Audiobooks.bundle-master so needed to rename to Audiobooks.bundle.

Also had to restart plex for it to show up.

Thank you!

**Comment by Guruleenyc** [comment]
Where exactly did you place it? I use the unraid docker version of plex.

**Comment by robwent** [comment]
I'm using the snap so I think the location is probably different to docker.

**Comment by mrtargaryen** [comment]
> I'm using the snap so I think the location is probably different to docker.

I'm using a QNAP NAS and I'm just wondering where to place the file to get this to work with Plex? I have had a large collection of audiobooks from years ago I'd like to add to plex, this seems to be the only way. I'm not sure if it still works, I hope someone can point me in the right direction. Thanks.
