### ISSUE TITLE
Add another source

### ISSUE THREAD

**Issue by petrmenzel** [macr0dev/Audiobooks.bundle#8]
As for me, my books were not found. I find them here: https://www.audiolibrix.com/en. What about to build something like this but for audiobooks? http://thetvdb.com/

**Comment by macr0dev** [comment]
The goal for this project is to make use of an existing source of information.  Audible is the most complete source I have found for Audiobooks that I could easily scrap.

If someone wanted to build a site and populate it with audiobooks, I'd be happy to scrape it instead.  Unfortunately, a quick search of the most popular books I've listened to do not show up on that site you listed.
